module-name: btp-operator
rc-tag: 1.1.3
protecode:
  - europe-docker.pkg.dev/kyma-project/pod/btp-manager:1.1.3
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
