module-name: btp-operator
rc-tag: 0.4.8
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.4.8
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
