module-name: btp-operator
rc-tag: 1.0.6
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.0.6
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
