module-name: btp-operator
rc-tag: 0.5.01
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.5.01
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
