module-name: btp-operator
rc-tag: 0.0.19.18
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:0.0.19.18
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
