name: Enable auto merge

on:
  pull_request:
    branches: [main, sm-integration]
    types:
    - opened
    - reopened
    - ready_for_review
    - synchronize

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge -A ${{ env.GIT_NAME }} --auto --squash "$PR_URL"
