name: Auto-merge

on:
  pull_request:
    branches: [main, sm-integration]
    types:
    - opened
    - reopened
    - ready_for_review

#a
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --merge "$PR_URL" --squash
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}