name: Enable auto merge

env:
  GIT_EMAIL: team-gopher+1@sap.com
  GIT_NAME: kyma-gopher-bot

on:
  pull_request:
    branches: [main, sm-integration]
    types:
    - opened
    - reopened
    - ready_for_review
    - synchronize

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for PRs
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.BOT_TOKEN}}
        run: gh pr merge -A ${{ env.GIT_NAME }} --auto --squash "$PR_URL"
