# Call this workflow from other jobs to wait for artifacts

name: Await artifacts (reusable)

on:
  workflow_call:
    inputs:
      image-repo:
        description: Binary image registry reference
        required: true
        type: string
      module-repo:
        description: OCI module image registry reference
        required: true
        type: string
      image-tag:
        description: Binary image tag
        required: true
        type: string
      module-tag:
        description: OCI module image tag
        required: true
        type: string

jobs:
  await-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Wait for artifacts
        env:
          BTP_OPERATOR_REPO: ${{ inputs.module-repo }}
          BTP_MANAGER_REPO: ${{ inputs.image-repo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/await_artifacts.sh ${{ inputs.image-tag }} ${{ inputs.module-tag }}"

      - name: Wait for post-btp-manager-module-build status
        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
        id: wait-for-module-build-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "post-btp-manager-module-build"
          timeoutSeconds: "300"

      - name: Check if post-btp-manager-module-build status is success
        if: steps.wait-for-module-build-status.state != 'success'
        run: |
            echo 'post-btp-manager-module-build failed.'
            exit 1

      - name: Wait for post-btp-manager-build status
        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
        id: wait-for-image-build-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "post-btp-manager-build"
          timeoutSeconds: "300"

      - name: Check if post-btp-manager-build status is success
        if: steps.wait-for-image-build-status.state != 'success'
        run: |
          echo 'post-btp-manager-build failed.'
          exit 1
