name: "Create PR"

on:
    workflow_dispatch:
      inputs:
        name:
          description: 'Create PR'
          default: ""
          required: true
        credentials:
          type: boolean
          description: Create PR during release
          default: true


jobs:
  validate-release:
    name: Validate release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update chart and module resources
        env:
          GH_TOKEN: ${{ secrets.GH_TEST }}
        run: |
          prs=$(gh pr list -A MarekMichali --state open --json headRefName | jq -r '.[] | .headRefName')
          echo $prs
          scripts/create_scan_config.sh ${{ inputs.name }}
          echo "BRANCH_NAME=sec_config_${{ inputs.name }}" >> $GITHUB_ENV
          
          git add sec-scanners-config.yaml
          git stash push --staged
          git checkout --force -B main refs/remotes/origin/main
          git checkout -B sec_config_${{ inputs.name }}
          git stash apply
          git add sec-scanners-config.yaml
          git config --global user.email marek.michali@sap.com
          git config --global user.name MarekMichali
          git commit -m "Test commit"
          echo "remote"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TEST }}@github.com/MarekMichali/btp-manager.git
          echo "push"
          git push --set-upstream origin sec_config_${{ inputs.name }} -f
          echo "pr"
          resp=$(gh pr create -B main --title "Test commit" --body "Test body" | tail -n 1)
          echo "resp"
          echo $resp
          