
name: "Create my release with dsc"

env:
  BTP_MANAGER_REPO: docker://europe-docker.pkg.dev/kyma-project/prod/btp-manager
  BTP_OPERATOR_REPO: docker://europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release version'
        default: ""
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: |
          CHANGELOG=$(git log --pretty=format: '%h %s' --no-merges $(git describe --tags --abbrev=0 HEAD^)..HEAD)
          RELEASE_DESCRIPTION="Changes in this Release\n\n$CHANGELOG"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.name }}
          release_name: Release ${{ github.event.inputs.name }}
          body: ${{ env.RELEASE_DESCRIPTION}}
          draft: false
          prerelease: false
   