name: "Create PR"

env:
    KYMA_BTP_MANAGER_REPO: ${{ github.repository_owner }}/btp-manager
    GIT_EMAIL: marek.michali@sap.com
    GIT_NAME: MarekMichali
    BRANCH_NAME: sec-scanners-config-${{ inputs.name }}
on:
    workflow_dispatch:
      inputs:
        name:
          description: 'Create PR'
          default: ""
          required: true
        credentials:
          type: boolean
          description: Create PR during release
          default: true


jobs:
  validate-release:
    name: Validate release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump 
        env:
          GH_TOKEN: ${{ secrets.GH_TEST }}
        run: |
          scripts/create_scan_config.sh ${{ inputs.name }}
          prs=$(gh pr list -A ${{ env.GIT_NAME }} --state open --json headRefName | jq -r '.[] | .headRefName')
          if echo $prs | tr " " '\n' | grep -F -q -x ${{ env.BRANCH_NAME }}; then
            echo "PR already exists, no need to create a new one"
          elif [ -z "$(git status --porcelain)" ]; then
            echo "nothing changed, no need to create PR"
          else
            scripts/create_pr.sh ${{ inputs.name }}
          fi 

          