
name: "Create my release with dsc"

#env:
 # BTP_MANAGER_REPO: docker://europe-docker.pkg.dev/kyma-project/prod/btp-manager
  #BTP_OPERATOR_REPO: docker://europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release version'
        default: ""
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Generate Changelog
        run: |
          git describe --tags --abbrev=0
          LATEST_RELEASE=$(git describe --tags $(git rev-list --tags --max-count=1))
          git log 0.0.19.1..0.0.19.2 --pretty=format:"%h" > CHANGELOG.md
          while read -r line; do
          echo "$line"
          git log --pretty=format:"%h %s" main | grep "$line" | grep -o " (#[0-9]\+)" | grep -o "[0-9]\+" | awk '{print "in https://github.com/kyma-project/btp-manager/pull/" $1}'
          done < "CHANGELOG.md"
         # git log $LATEST_RELEASE..HEAD --pretty=format:"* %s by %an in %h " > CHANGELOG.md
        #  git log $LATEST_RELEASE..HEAD --pretty=format:"* %s by %an in %h "
    #  - name: Create Release
     #   id: create_release
      #  uses: actions/create-release@v1
       # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
         # tag_name: ${{ github.event.inputs.name }}
          #release_name: Release ${{ github.event.inputs.name }}
          #body: |
           # Changes in this Release
            #  - TBD
          #draft: false
          #prerelease: false
   