name: Create Issue from Template

on:
  workflow_dispatch:
    inputs:
      issue_template:
        description: 'Issue template to use (bug-report, feature-request, documentation-improvement, etc.)'
        required: true
        default: 'bug-report'
      issue_title:
        description: 'Title of the issue'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download logs from all attempts of latest workflow run by workflow name and title
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          workflow_title_filter="Create release ${{ github.event.inputs.issue_title }}"
          workflow_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/workflows" | jq -r '.workflows[] | select(.name == "Create release") | .id')
          if [ -z "$workflow_id" ] || [ "$workflow_id" = "null" ]; then
            echo "Release workflow not found."
            exit 1
          fi
          run_id=$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow_id}/runs" | jq -r --arg workflow_title_filter "$workflow_title_filter" '.workflow_runs[] | select(.display_title | test($workflow_title_filter; "i")) | .id' | head -n 1)
          if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then
            echo "No runs found for workflow: Create release with title filter: $workflow_title_filter"
            exit 1
          fi
          attempts=$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}" | jq -r '.run_attempt')
          if [ -z "$attempts" ] || [ "$attempts" = "null" ]; then
            echo "Attempts not found."
            exit 1
          fi
          for attempt in $(seq 1 $attempts); do
            echo "Downloading logs for attempt $attempt..."
            gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/${GITHUB_REPOSITORY}/actions/runs/${run_id}/attempts/${attempt}/logs" > "logs_attempt_${attempt}.zip"
          done

