name: Create Issue from Template

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: number

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download logs from all attempts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/download_workflow_logs.sh "Create release" "Create release ${{ github.event.inputs.version }}"

