name: "Create release"
run-name: Create release ${{ inputs.name }}

env:
  IMAGE_REPO: europe-docker.pkg.dev/kyma-project/prod/btp-manager
  KYMA_BTP_MANAGER_REPO: ${{ github.repository_owner }}/btp-manager
  GIT_EMAIL: team-gopher+1@sap.com
  GIT_NAME: kyma-gopher-bot
  BRANCH_NAME: sec-scanners-config-${{ inputs.name }}

permissions:
  contents: write
  id-token: write
  
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Create release'
        default: ""
        required: true
      credentials:
        type: choice
        description: SM credentials
        default: real
        options:
          - dummy
          - real
      skip-sec-file-bump:
        type: boolean
        description: 'Do not bump sec-scanners-config file'
        default: false
      dry-run:
        type: boolean
        description: 'Do not publish'
        default: false

jobs:
  create-draft-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ inputs.name }}" --title "${{ inputs.name }}" --notes "Draft release for ${{ inputs.name }}" --draft=true --repo "$GITHUB_REPOSITORY"

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: create-draft-release
    steps:
      - name: Publish draft release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh release edit "${{ inputs.name }}" --draft=false --repo "$GITHUB_REPOSITORY"
      - name: Wait for 1 minute
        run: sleep 60