name: "Create release"

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Create release'
        default: ""
        required: true
      credentials:
        type: choice
        description: SM credentials
        default: real
        options:
          - dummy
          - real

jobs:
  run-unit-tests:
    name: Unit tests
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"

  run-e2e-tests:
    name: E2E tests
    needs: run-unit-tests
    uses: "./.github/workflows/run-e2e-tests-reusable.yaml"
    secrets: inherit
    with:
      image-tag: ${{ github.event.inputs.name }}
      module-tag: v${{ github.event.inputs.name }}
      image-repo: europe-docker.pkg.dev/kyma-project/prod/btp-manager
      module-repo: europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator
      credentials-mode: ${{ github.event.inputs.credentials }}

  create-draft:
    name: Create draft release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/create_changelog.sh ${{ github.event.inputs.name }}
      - name: Create draft release
        id: create-draft
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { name, credentials } = context.payload.inputs;
            const fs = require('fs');

            try {
              try {
                bodyFileContent = fs.readFileSync('./CHANGELOG.md', { encoding: 'utf8' });
              } catch (error) {
                core.setFailed(error.message);
              }
              const response = await github.rest.repos.createRelease({
                draft: true,
                name: name,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: name,
                body: bodyFileContent,
              });
              const {
                data: { id: releaseId, html_url: htmlUrl, upload_url: uploadUrl }
              } = response;
              core.setOutput('id', releaseId);
              core.setOutput('html_url', htmlUrl);
              core.setOutput('upload_url', uploadUrl);

            } catch (error) {
              core.setFailed(error.message);
            }
      - name: Create lightweight tag
        run: |
          git tag ${{ github.event.inputs.name }}
          git push origin ${{ github.event.inputs.name }}

    outputs:
      release_id: ${{ steps.create-draft.outputs.id }}

  publish-release:
    name: Publish release
    needs: [create-draft]
    runs-on: ubuntu-latest

    steps:
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create-draft.outputs.release_id }}
