
name: "Create my release with dsc"

#env:
 # BTP_MANAGER_REPO: docker://europe-docker.pkg.dev/kyma-project/prod/btp-manager
  #BTP_OPERATOR_REPO: docker://europe-docker.pkg.dev/kyma-project/prod/unsigned/component-descriptors/kyma.project.io/module/btp-operator

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release version'
        default: ""
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPOSITORY='MarekMichali/btp-manager'
          LATEST_RELEASE_TAG=0.0.19.1       
          COMMITS_SINCE_LATEST_RELEASE=($(git log $LATEST_RELEASE_TAG..HEAD --pretty=format:"%h"))
              
          for line in "${COMMITS_SINCE_LATEST_RELEASE[@]}"; do
            git log $LATEST_RELEASE_TAG..HEAD --pretty=format:"* %s by @ %h" | grep "$line" | awk '{$NF=""; print $0}' | tr -d "\n" | sed 's/.$//' >> CHANGELOG.txt
            curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/$REPOSITORY/commits/$line | jq -r '.author.login' >> CHANGELOG.txt
          done
          echo "## What's Changed" >> CHANGELOG.md
          if [ -e CHANGELOG.txt ]; then
            tac CHANGELOG.txt >> CHANGELOG.md
          fi

          curl -s "https://api.github.com/repos/$REPOSITORY/compare/$(git rev-list --max-parents=0 HEAD)...$LATEST_RELEASE_TAG" | jq -r '.commits[].author.login' | sort -u >CONTRIBUTORS_BEFORE_NEW_RELEASE.txt
          curl -s "https://api.github.com/repos/$REPOSITORY/compare/$LATEST_RELEASE_TAG...HEAD" | jq -r '.commits[].author.login' | sort -u >RELEASE_CONTRIBUTORS.txt
          join -v2 CONTRIBUTORS_BEFORE_NEW_RELEASE.txt RELEASE_CONTRIBUTORS.txt >NEW_CONTRIBUTORS.txt

          if [ -s NEW_CONTRIBUTORS.txt ]; then
              echo -e "\n## New Contributors" >> CHANGELOG.md
              echo "* @szwedm made their first contribution in " | tr -d "\n" >> CHANGELOG.md
              grep @szwedm CHANGELOG.md | head -1 | grep -o " (#[0-9]\+)" >> CHANGELOG.md
              while read line; do
                echo "* @$i made their first contribution in " | tr -d "\n" >> CHANGELOG.md
                grep @$i CHANGELOG.md | head -1 | grep -o " (#[0-9]\+)" >> CHANGELOG.md
              done < NEW_CONTRIBUTORS.txt
          fi
          
          echo -e "\n**Full Changelog**: https://github.com/$REPOSITORY/compare/$(git rev-list --max-parents=0 HEAD)...${{ github.event.inputs.name }}" >> CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.name }}
          release_name: Release ${{ github.event.inputs.name }}
          body: |
            Changes in this release
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
   