# Call this workflow from other jobs to execute unit tests in the current context

name: Run unit tests (reusable)

on:
  workflow_call:
    inputs:
      release:
        description: 'Determines if the workflow is called from release'
        default: "true"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
      with:
        files: |
          api/**
          cmd/**
          config/**
          controllers/**
          deployments/**
          examples/**
          hack/**
          internal/**
          module-chart/**
          module-resources/**
          scripts/**
          config.yaml
          Dockerfile
          go.mod
          go.sum
          main.go
          Makefile

    - name: Set up go environment
      if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Run make test
      if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
      run: make test
