name: Run unit tests

on:
  push:
    branches: [main, sm-integration]
  pull_request:
    # Trigger for Pull Request
    branches: [main, sm-integration]

jobs:
  run-unit-tests:
    uses: "./.github/workflows/run-unit-tests-reusable.yaml"
    if: ${{ !github.event.pull_request.user.login == 'kyma-gopher-bot' }}
    with:
      release: "false"
