# Call this workflow from other jobs to execute e2e tests

name: Run E2E tests on the cluster (reusable)

on:
  workflow_call:
    inputs:
      image-repo:
        description: Binary image registry reference
        required: true
        type: string
      image-tag:
        description: Binary image tag
        required: true
        type: string
      credentials-mode:
        description: real or dummy credentials
        required: true
        type: string
      last-k3s-versions:
        description: number of the most recent K3s versions to be used
        required: false
        default: 1
        type: string
      release:
        description: 'Determines if the workflow is called from release'
        default: "true"
        type: string


jobs:
  prepare-tests:
    # job waits until Prow job uploads docker image
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-versions.outputs.k3s_versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            api/**
            cmd/**
            config/**
            controllers/**
            deployments/**
            examples/**
            hack/**
            internal/**
            module-chart/**
            module-resources/**
            scripts/**
            config.yaml
            Dockerfile
            go.mod
            go.sum
            main.go
            Makefile

      - id: get-versions
        name: Get K3s versions
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        # prepare json representing GitHub matrix:
        # {"include": [
        #    {"version":"v1.26.10+k3s1"},
        #      ...
        #    {"version":"v1.28.3+k3s1"}
        # ]
        # }
        run: |
          VERSIONS=($(./scripts/testing/get-latest-k3s-releases.sh ${{ inputs.last-k3s-versions }}))
          MATRIX_AS_JSON=$(echo ${VERSIONS[*]} | awk 'END {printf "{\"include\":[";for (i = 1; i < NF; i++) printf "{\"version\":%s},",$i;printf "{\"version\":%s}]}",$i }'|jq -c)
          echo "k3s_versions=${MATRIX_AS_JSON}" >> "${GITHUB_OUTPUT}"

      - name: Wait for artifacts
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        env:
          IMAGE_REPO: ${{ inputs.image-repo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/await_image.sh ${{ inputs.image-tag }}"

  run-e2e-matrix:
    runs-on: ubuntu-latest
    needs: prepare-tests
    timeout-minutes: 5
    strategy:
      matrix: ${{ fromJSON(needs.prepare-tests.outputs.versions) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            api/**
            cmd/**
            config/**
            controllers/**
            deployments/**
            examples/**
            hack/**
            internal/**
            module-chart/**
            module-resources/**
            scripts/**
            config.yaml
            Dockerfile
            go.mod
            go.sum
            main.go
            Makefile

      - name: Prepare K3s cluster and docker registry
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: "./scripts/testing/k3s-setup.sh ${{ matrix.version }} --wait"

      - name: Set up go environment
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install BTP operator
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        env:
          SM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          SM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SM_URL: ${{ secrets.SM_URL }}
          SM_TOKEN_URL: ${{ secrets.TOKENURL }}
        run: "./scripts/testing/install_module.sh ${{ inputs.image-repo }}:${{ inputs.image-tag }} ${{ inputs.credentials-mode }} ci"

      - name: Run tests
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: "./scripts/testing/run_e2e_module_tests.sh ${{ inputs.credentials-mode }} ci"

  confirm-matrix-tests-succeeded:
    runs-on: ubuntu-latest
    needs: run-e2e-matrix
    if: success()
    outputs:
      success: ${{ steps.set-output.outputs.success }}
    steps:
      - name: Confirm that matrix tests succeeded
        id: set-output
        run: echo "success=true" >> "${GITHUB_OUTPUT}"

  finish-e2e-tests:
    runs-on: ubuntu-latest
    needs: confirm-matrix-tests-succeeded
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@90a06d6ba9543371ab4df8eeca0be07ca6054959
        with:
          files: |
            api/**
            cmd/**
            config/**
            controllers/**
            deployments/**
            examples/**
            hack/**
            internal/**
            module-chart/**
            module-resources/**
            scripts/**
            config.yaml
            Dockerfile
            go.mod
            go.sum
            main.go
            Makefile

      - name: Final decision
        if: ${{ steps.changed-files-specific.outputs.any_modified == 'true' || inputs.release == 'true' }}
        run: |
          [[ "${{ needs.confirm-matrix-tests-succeeded.outputs.success }}" != "true"  ]] && echo "E2E tests failed" && exit 1
          echo "E2E tests passed"