name: Label validator
on:
  pull_request:
    types: ["opened", "reopened", "edited", "closed", "labeled", "unlabeled"]
    branches: [ "main" ]

jobs:
  wait-for-prow-jobs:
    name: Wait for prow jobs
    runs-on: ubuntu-latest
    steps:
      - name: Wait for post-btp-manager-module-build status
        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
        id: wait-for-module-build-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "post-btp-manager-module-build"
          timeoutSeconds: "300"

      - name: Check if post-btp-manager-module-build status is success
        if: steps.wait-for-module-build-status.state != 'success'
        run: |
          echo 'post-btp-manager-module-build failed.'
          exit 1

      - name: Wait for post-btp-manager-build status
        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
        id: wait-for-image-build-status
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "post-btp-manager-build"
          timeoutSeconds: "300"

      - name: Check if post-btp-manager-build status is success
        if: steps.wait-for-image-build-status.state != 'success'
        run: |
          echo 'post-btp-manager-build failed.'
          exit 1