name: Upload Release Logs as Assets

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: number

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download logs from all attempts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/download_workflow_logs.sh "Create release" "Create release ${{ github.event.inputs.version }}"

      - name: Upload logs as release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in logs_attempt_*.zip; do
            echo "Uploading $file to release ${{ github.event.inputs.version }}..."
            gh release upload ${{ github.event.inputs.version }} "$file" --repo "$GITHUB_REPOSITORY" --clobber
          done
