name: Upload Release Logs as Assets

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: number

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Wait for 'Create release' workflow to finish if in progress
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if a 'Create release' workflow is in progress..."
          while true; do
            IN_PROGRESS=$(gh run list --workflow "Create release" --json status -L 1 --jq '.[] | select(.status == "in_progress" or .status == "queued") | .status')
            if [ -z "$IN_PROGRESS" ]; then
              echo "No 'Create release' workflow in progress."
              break
            fi
            echo "'Create release' workflow is in progress. Waiting 30 seconds..."
            sleep 30
          done

      - name: Download logs from all attempts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/download_workflow_logs.sh "Create release" "Create release ${{ github.event.inputs.version || github.event.release.tag_name }}"

      - name: Upload logs as release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in logs_attempt_*.zip; do
            echo "Uploading $file to release ${{ github.event.inputs.version || github.event.release.tag_name }}..."
            gh release upload ${{ github.event.inputs.version || github.event.release.tag_name }} "$file" --repo "$GITHUB_REPOSITORY" --clobber
          done
